//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class sinfo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string sinfo_mob { get; set; }
        public Nullable<System.DateTime> registeredon { get; set; }
    }
}
